# Generated by Django 3.2.11 on 2022-04-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'A'), (2, 'B')])),
            ],
        ),
    ]
