# Generated by Django 3.2.11 on 2022-04-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosperi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='type',
        ),
        migrations.AddField(
            model_name='bucket',
            name='price',
            field=models.IntegerField(choices=[(10, 'A'), (20, 'B')], default=10),
        ),
    ]
